
package com.ync365.seed.commons.sms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceSoap {


    /**
     * 发送短信：sn软件序列号;pwd序列号密码;mobile手机号列表，以逗号,隔开;content发送内容
     * 
     * @param mobile
     * @param sn
     * @param pwd
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendSMS", action = "http://tempuri.org/SendSMS")
    @WebResult(name = "SendSMSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendSMS", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.SendSMS")
    @ResponseWrapper(localName = "SendSMSResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.SendSMSResponse")
    public String sendSMS(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content);

    /**
     * 发送短信：sn软件序列号;pwd序列号密码;mobile手机号列表，以逗号,隔开;content发送内容;rrid唯一标识,全数字
     * 
     * @param mobile
     * @param sn
     * @param pwd
     * @param content
     * @param rrid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendSMS_R", action = "http://tempuri.org/SendSMS_R")
    @WebResult(name = "SendSMS_RResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendSMS_R", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.SendSMSR")
    @ResponseWrapper(localName = "SendSMS_RResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.SendSMSRResponse")
    public String sendSMSR(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        String rrid);

    /**
     * 发送短信（可扩展）：sn软件序列号;pwd序列号密码;mobile手机号列表，以逗号,隔开;content发送内容;subcode最长9位数字扩展码
     * 
     * @param mobile
     * @param subcode
     * @param sn
     * @param pwd
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendSMSEx", action = "http://tempuri.org/SendSMSEx")
    @WebResult(name = "SendSMSExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendSMSEx", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.SendSMSEx")
    @ResponseWrapper(localName = "SendSMSExResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.SendSMSExResponse")
    public String sendSMSEx(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "subcode", targetNamespace = "http://tempuri.org/")
        String subcode);

    /**
     * 发送短信（可扩展）：sn软件序列号;pwd序列号密码;mobile手机号列表，以逗号,隔开;content发送内容;subcode最长9位数字扩展码;rrid唯一标识,全数字
     * 
     * @param mobile
     * @param subcode
     * @param sn
     * @param pwd
     * @param content
     * @param rrid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendSMSEx_R", action = "http://tempuri.org/SendSMSEx_R")
    @WebResult(name = "SendSMSEx_RResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendSMSEx_R", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.SendSMSExR")
    @ResponseWrapper(localName = "SendSMSEx_RResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.SendSMSExRResponse")
    public String sendSMSExR(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "subcode", targetNamespace = "http://tempuri.org/")
        String subcode,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        String rrid);

    /**
     * 注销：sn软件序列号;pwd序列号密码
     * 
     * @param sn
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UnRegister", action = "http://tempuri.org/UnRegister")
    @WebResult(name = "UnRegisterResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UnRegister", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.UnRegister")
    @ResponseWrapper(localName = "UnRegisterResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.UnRegisterResponse")
    public String unRegister(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 充值：sn软件序列号;pwd序列号密码;cardno充值卡号;cardpwd充值卡密码
     * 
     * @param cardpwd
     * @param sn
     * @param pwd
     * @param cardno
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ChargUp", action = "http://tempuri.org/ChargUp")
    @WebResult(name = "ChargUpResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ChargUp", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.ChargUp")
    @ResponseWrapper(localName = "ChargUpResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.ChargUpResponse")
    public String chargUp(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "cardno", targetNamespace = "http://tempuri.org/")
        String cardno,
        @WebParam(name = "cardpwd", targetNamespace = "http://tempuri.org/")
        String cardpwd);

    /**
     * 获取余额：sn软件序列号;pwd序列号密码
     * 
     * @param sn
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBalance", action = "http://tempuri.org/GetBalance")
    @WebResult(name = "GetBalanceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBalance", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.GetBalance")
    @ResponseWrapper(localName = "GetBalanceResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.GetBalanceResponse")
    public String getBalance(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 获取软件序列号状态：sn软件序列号;pwd序列号密码
     * 
     * @param sn
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetStatus", action = "http://tempuri.org/GetStatus")
    @WebResult(name = "GetStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStatus", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.GetStatus")
    @ResponseWrapper(localName = "GetStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.GetStatusResponse")
    public String getStatus(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 获取特服号：sn软件序列号;pwd序列号密码
     * 
     * @param sn
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCode", action = "http://tempuri.org/GetCode")
    @WebResult(name = "GetCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCode", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.GetCode")
    @ResponseWrapper(localName = "GetCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.GetCodeResponse")
    public String getCode(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 更改密码：sn软件序列号;pwd序列号密码;newpwd新密码
     * 
     * @param newpwd
     * @param sn
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UDPPwd", action = "http://tempuri.org/UDPPwd")
    @WebResult(name = "UDPPwdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UDPPwd", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.UDPPwd")
    @ResponseWrapper(localName = "UDPPwdResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.UDPPwdResponse")
    public String udpPwd(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "newpwd", targetNamespace = "http://tempuri.org/")
        String newpwd);

    /**
     * 更改签名：sn软件序列号;pwd序列号密码;sign企业签名(2-15个字符)
     * 
     * @param sign
     * @param sn
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UDPSIGN", action = "http://tempuri.org/UDPSIGN")
    @WebResult(name = "UDPSIGNResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UDPSIGN", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.UDPSIGN")
    @ResponseWrapper(localName = "UDPSIGNResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.UDPSIGNResponse")
    public String udpsign(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "sign", targetNamespace = "http://tempuri.org/")
        String sign);

    /**
     * 更改签名（网络版）：sn软件序列号;pwd序列号密码;sign企业签名(2-15个字符);subcode最长9位数字扩展码;comName企业全称
     * 
     * @param sign
     * @param subcode
     * @param sn
     * @param comName
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UDPSIGNEX", action = "http://tempuri.org/UDPSIGNEX")
    @WebResult(name = "UDPSIGNEXResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UDPSIGNEX", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.UDPSIGNEX")
    @ResponseWrapper(localName = "UDPSIGNEXResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.UDPSIGNEXResponse")
    public String udpsignex(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "subcode", targetNamespace = "http://tempuri.org/")
        String subcode,
        @WebParam(name = "sign", targetNamespace = "http://tempuri.org/")
        String sign,
        @WebParam(name = "comName", targetNamespace = "http://tempuri.org/")
        String comName);

    /**
     * 接收短信：sn软件序列号;pwd序列号密码。total_num为负数，表示操作失败
     * 
     * @param sn
     * @param pwd
     * @return
     *     returns com.ync365.seed.commons.sms.ArrayOfMOBody
     */
    @WebMethod(operationName = "RECSMS", action = "http://tempuri.org/RECSMS")
    @WebResult(name = "RECSMSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RECSMS", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.RECSMS")
    @ResponseWrapper(localName = "RECSMSResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.RECSMSResponse")
    public ArrayOfMOBody recsms(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 网络版接收短信：sn软件序列号;pwd序列号密码;subcode子号码。total_num为负数，表示操作失败
     * 
     * @param subcode
     * @param sn
     * @param pwd
     * @return
     *     returns com.ync365.seed.commons.sms.ArrayOfMOBody
     */
    @WebMethod(operationName = "RECSMSEx", action = "http://tempuri.org/RECSMSEx")
    @WebResult(name = "RECSMSExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RECSMSEx", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.RECSMSEx")
    @ResponseWrapper(localName = "RECSMSExResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.RECSMSExResponse")
    public ArrayOfMOBody recsmsEx(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "subcode", targetNamespace = "http://tempuri.org/")
        String subcode);

    /**
     * 接收短信utf-8编码：sn软件序列号;pwd序列号密码。total_num为负数，表示操作失败
     * 
     * @param sn
     * @param pwd
     * @return
     *     returns com.ync365.seed.commons.sms.ArrayOfMOBody
     */
    @WebMethod(operationName = "RECSMS_UTF8", action = "http://tempuri.org/RECSMS_UTF8")
    @WebResult(name = "RECSMS_UTF8Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RECSMS_UTF8", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.RECSMSUTF8")
    @ResponseWrapper(localName = "RECSMS_UTF8Response", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.RECSMSUTF8Response")
    public ArrayOfMOBody recsmsUTF8(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 网络版接收短信utf-8编码：sn软件序列号;pwd序列号密码;subcode子号码。total_num为负数，表示操作失败
     * 
     * @param subcode
     * @param sn
     * @param pwd
     * @return
     *     returns com.ync365.seed.commons.sms.ArrayOfMOBody
     */
    @WebMethod(operationName = "RECSMSEx_UTF8", action = "http://tempuri.org/RECSMSEx_UTF8")
    @WebResult(name = "RECSMSEx_UTF8Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RECSMSEx_UTF8", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.RECSMSExUTF8")
    @ResponseWrapper(localName = "RECSMSEx_UTF8Response", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.RECSMSExUTF8Response")
    public ArrayOfMOBody recsmsExUTF8(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "subcode", targetNamespace = "http://tempuri.org/")
        String subcode);

    /**
     * 软件序列号注册：sn软件序列号;pwd序列号密码;province省;city城市;trade行业;entname企业名称;linkman联系人;phone联系电话;mobile移动电话;email邮件地址;fax传真;address地址;postcode邮政编码
     * 
     * @param address
     * @param city
     * @param mobile
     * @param postcode
     * @param sign
     * @param linkman
     * @param trade
     * @param province
     * @param phone
     * @param entname
     * @param sn
     * @param pwd
     * @param fax
     * @param email
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Register", action = "http://tempuri.org/Register")
    @WebResult(name = "RegisterResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Register", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.Register")
    @ResponseWrapper(localName = "RegisterResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.RegisterResponse")
    public String register(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "province", targetNamespace = "http://tempuri.org/")
        String province,
        @WebParam(name = "city", targetNamespace = "http://tempuri.org/")
        String city,
        @WebParam(name = "trade", targetNamespace = "http://tempuri.org/")
        String trade,
        @WebParam(name = "entname", targetNamespace = "http://tempuri.org/")
        String entname,
        @WebParam(name = "linkman", targetNamespace = "http://tempuri.org/")
        String linkman,
        @WebParam(name = "phone", targetNamespace = "http://tempuri.org/")
        String phone,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "email", targetNamespace = "http://tempuri.org/")
        String email,
        @WebParam(name = "fax", targetNamespace = "http://tempuri.org/")
        String fax,
        @WebParam(name = "address", targetNamespace = "http://tempuri.org/")
        String address,
        @WebParam(name = "postcode", targetNamespace = "http://tempuri.org/")
        String postcode,
        @WebParam(name = "sign", targetNamespace = "http://tempuri.org/")
        String sign);

    /**
     * 获取软件序列号子号码长度：sn软件序列号;pwd序列号密码
     * 
     * @param sn
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFlag", action = "http://tempuri.org/GetFlag")
    @WebResult(name = "GetFlagResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFlag", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.GetFlag")
    @ResponseWrapper(localName = "GetFlagResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.GetFlagResponse")
    public String getFlag(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 通道测试：sn软件序列号;pwd序列号密码;mobile手机号列表，最多20个，以逗号,隔开
     * 
     * @param mobile
     * @param sn
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SMSTest", action = "http://tempuri.org/SMSTest")
    @WebResult(name = "SMSTestResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SMSTest", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.SMSTest")
    @ResponseWrapper(localName = "SMSTestResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.SMSTestResponse")
    public String smsTest(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        String mobile);

    /**
     * 编解码：content中文内容;code编解码类型;type，0编码1解码
     * 
     * @param code
     * @param type
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TestCode", action = "http://tempuri.org/TestCode")
    @WebResult(name = "TestCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TestCode", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.TestCode")
    @ResponseWrapper(localName = "TestCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.TestCodeResponse")
    public String testCode(
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "code", targetNamespace = "http://tempuri.org/")
        String code,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        String type);

    /**
     * 获取软件序列号参数：sn软件序列号;pwd序列号密码;
     * 
     * @param sn
     * @param pwd
     * @return
     *     returns com.ync365.seed.commons.sms.RegistryInfo
     */
    @WebMethod(operationName = "GetAllInfo", action = "http://tempuri.org/GetAllInfo")
    @WebResult(name = "GetAllInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllInfo", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.GetAllInfo")
    @ResponseWrapper(localName = "GetAllInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.GetAllInfoResponse")
    public RegistryInfo getAllInfo(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 获取软件序列号2参数：sn软件序列号;pwd序列号密码;
     * 
     * @param ver
     * @param oem
     * @param sn
     * @param pwd
     * @return
     *     returns com.ync365.seed.commons.sms.RegistryInfo2
     */
    @WebMethod(operationName = "GetAllInfo2", action = "http://tempuri.org/GetAllInfo2")
    @WebResult(name = "GetAllInfo2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllInfo2", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.GetAllInfo2")
    @ResponseWrapper(localName = "GetAllInfo2Response", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.GetAllInfo2Response")
    public RegistryInfo2 getAllInfo2(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "ver", targetNamespace = "http://tempuri.org/")
        String ver,
        @WebParam(name = "oem", targetNamespace = "http://tempuri.org/")
        String oem);

    /**
     * 设置高端发送：sn软件序列号;pwd序列号密码;gd参数1普通通道2高端通道;
     * 
     * @param sn
     * @param pwd
     * @param gd
     * @return
     *     returns double
     */
    @WebMethod(operationName = "SetGaoDuan", action = "http://tempuri.org/SetGaoDuan")
    @WebResult(name = "SetGaoDuanResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetGaoDuan", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.SetGaoDuan")
    @ResponseWrapper(localName = "SetGaoDuanResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.SetGaoDuanResponse")
    public double setGaoDuan(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "gd", targetNamespace = "http://tempuri.org/")
        String gd);

    /**
     * 获取高端发送：sn软件序列号;pwd序列号密码;
     * 
     * @param sn
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetGaoDuan", action = "http://tempuri.org/GetGaoDuan")
    @WebResult(name = "GetGaoDuanResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetGaoDuan", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.GetGaoDuan")
    @ResponseWrapper(localName = "GetGaoDuanResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.GetGaoDuanResponse")
    public String getGaoDuan(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 发送短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字.返回:唯一标识
     * 
     * @param ext
     * @param mobile
     * @param stime
     * @param sn
     * @param pwd
     * @param content
     * @param rrid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/mt")
    @WebResult(name = "mtResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mt", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.Mt")
    @ResponseWrapper(localName = "mtResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MtResponse")
    public String mt(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "ext", targetNamespace = "http://tempuri.org/")
        String ext,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        String stime,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        String rrid);

    /**
     * 发送短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字.返回:唯一标识
     * 
     * @param ext
     * @param mobile
     * @param stime
     * @param sn
     * @param pwd
     * @param content
     * @param rrid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/mdSmsSend")
    @WebResult(name = "mdSmsSendResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mdSmsSend", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdSmsSend")
    @ResponseWrapper(localName = "mdSmsSendResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdSmsSendResponse")
    public String mdSmsSend(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "ext", targetNamespace = "http://tempuri.org/")
        String ext,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        String stime,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        String rrid);

    /**
     * 发送短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容utf-8编码;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字.返回:唯一标识
     * 
     * @param ext
     * @param mobile
     * @param stime
     * @param sn
     * @param pwd
     * @param content
     * @param rrid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "mdSmsSend_u", action = "http://tempuri.org/mdSmsSend_u")
    @WebResult(name = "mdSmsSend_uResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mdSmsSend_u", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdSmsSendU")
    @ResponseWrapper(localName = "mdSmsSend_uResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdSmsSendUResponse")
    public String mdSmsSendU(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "ext", targetNamespace = "http://tempuri.org/")
        String ext,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        String stime,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        String rrid);

    /**
     * 发送短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容utf-8编码;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字.返回:唯一标识
     * 
     * @param ext
     * @param mobile
     * @param stime
     * @param sn
     * @param pwd
     * @param content
     * @param rrid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "mdSmsSend_DES", action = "http://tempuri.org/mdSmsSend_DES")
    @WebResult(name = "mdSmsSend_DESResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mdSmsSend_DES", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdSmsSendDES")
    @ResponseWrapper(localName = "mdSmsSend_DESResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdSmsSendDESResponse")
    public String mdSmsSendDES(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "ext", targetNamespace = "http://tempuri.org/")
        String ext,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        String stime,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        String rrid);

    /**
     * 发送短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容utf-8编码;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字.返回:唯一标识
     * 
     * @param ext
     * @param mobile
     * @param stime
     * @param sn
     * @param pwd
     * @param content
     * @param rrid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "mdSmsSend_AES", action = "http://tempuri.org/mdSmsSend_AES")
    @WebResult(name = "mdSmsSend_AESResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mdSmsSend_AES", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdSmsSendAES")
    @ResponseWrapper(localName = "mdSmsSend_AESResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdSmsSendAESResponse")
    public String mdSmsSendAES(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "ext", targetNamespace = "http://tempuri.org/")
        String ext,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        String stime,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        String rrid);

    /**
     * 发送短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字.返回:唯一标识
     * 
     * @param ext
     * @param mobile
     * @param stime
     * @param sn
     * @param pwd
     * @param content
     * @param rrid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "mdSmsSend_g", action = "http://tempuri.org/mdSmsSend_g")
    @WebResult(name = "mdSmsSend_gResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mdSmsSend_g", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdSmsSendG")
    @ResponseWrapper(localName = "mdSmsSend_gResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdSmsSendGResponse")
    public String mdSmsSendG(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "ext", targetNamespace = "http://tempuri.org/")
        String ext,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        String stime,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        String rrid);

    /**
     * 接收短信：sn软件序列号;pwd加密密码md5(sn+password).[优先使用本接口]
     * 
     * @param sn
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/mo")
    @WebResult(name = "moResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mo", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.Mo")
    @ResponseWrapper(localName = "moResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MoResponse")
    public String mo(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 接收短信：sn软件序列号;pwd加密密码md5(sn+password);maxID：上次接收最大id
     * 
     * @param maxID
     * @param sn
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/mo2")
    @WebResult(name = "mo2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mo2", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.Mo2")
    @ResponseWrapper(localName = "mo2Response", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.Mo2Response")
    public String mo2(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "maxID", targetNamespace = "http://tempuri.org/")
        int maxID);

    /**
     * 回执：sn软件序列号;pwd加密密码md5(sn+password);maxid最大id
     * 
     * @param maxid
     * @param sn
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/report")
    @WebResult(name = "reportResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "report", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.Report")
    @ResponseWrapper(localName = "reportResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.ReportResponse")
    public String report(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "maxid", targetNamespace = "http://tempuri.org/")
        long maxid);

    /**
     * 回执：sn软件序列号;pwd加密密码md5(sn+password);maxid最大id
     * 
     * @param maxid
     * @param sn
     * @param pwd
     * @param rrid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/report2")
    @WebResult(name = "report2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "report2", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.Report2")
    @ResponseWrapper(localName = "report2Response", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.Report2Response")
    public String report2(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "maxid", targetNamespace = "http://tempuri.org/")
        long maxid,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        String rrid);

    /**
     * 回执：sn软件序列号;pwd加密密码md5(sn+password);maxid最大id
     * 
     * @param maxid
     * @param sn
     * @param pwd
     * @param rrid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/report2DES")
    @WebResult(name = "report2DESResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "report2DES", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.Report2DES")
    @ResponseWrapper(localName = "report2DESResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.Report2DESResponse")
    public String report2DES(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "maxid", targetNamespace = "http://tempuri.org/")
        long maxid,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        String rrid);

    /**
     * 获取信息ID：sn软件序列号;pwd加密密码md5(sn+password)
     * 
     * @param sn
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/msgid")
    @WebResult(name = "msgidResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "msgid", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.Msgid")
    @ResponseWrapper(localName = "msgidResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MsgidResponse")
    public String msgid(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 查询余额：sn软件序列号;pwd加密密码md5(sn+password)
     * 
     * @param sn
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/balance")
    @WebResult(name = "balanceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "balance", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.Balance")
    @ResponseWrapper(localName = "balanceResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.BalanceResponse")
    public String balance(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 个性短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容,GB2312编码,以逗号,隔开;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字.返回:唯一标识
     * 
     * @param ext
     * @param mobile
     * @param stime
     * @param sn
     * @param pwd
     * @param content
     * @param rrid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/gxmt")
    @WebResult(name = "gxmtResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "gxmt", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.Gxmt")
    @ResponseWrapper(localName = "gxmtResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.GxmtResponse")
    public String gxmt(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "ext", targetNamespace = "http://tempuri.org/")
        String ext,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        String stime,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        String rrid);

    /**
     * 文件传输：sn软件序列号;pwd加密密码md5(sn+password);fname增值文件名;rrid第一个接口返回id;sort批次;total总次数;ftype类别1短信2彩信3语音4传真5邮件;content内容,base64编码.返回:rrid
     * 
     * @param fname
     * @param total
     * @param ftype
     * @param sn
     * @param sort
     * @param pwd
     * @param rrid
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/fileMT")
    @WebResult(name = "fileMTResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "fileMT", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.FileMT")
    @ResponseWrapper(localName = "fileMTResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.FileMTResponse")
    public String fileMT(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "fname", targetNamespace = "http://tempuri.org/")
        String fname,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        String rrid,
        @WebParam(name = "sort", targetNamespace = "http://tempuri.org/")
        int sort,
        @WebParam(name = "total", targetNamespace = "http://tempuri.org/")
        int total,
        @WebParam(name = "ftype", targetNamespace = "http://tempuri.org/")
        int ftype,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content);

    /**
     * 彩信文件传输：sn软件序列号;pwd加密密码md5(sn+password);rrid第一个接口返回id;content内容,base64编码.返回:rrid
     * 
     * @param sn
     * @param pwd
     * @param rrid
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/mmsFileMT")
    @WebResult(name = "mmsFileMTResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mmsFileMT", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MmsFileMT")
    @ResponseWrapper(localName = "mmsFileMTResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MmsFileMTResponse")
    public String mmsFileMT(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        String rrid,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content);

    /**
     * 彩信发送：sn软件序列号;pwd加密密码md5(sn+password);title彩信主题;mobile手机号码,以英文逗号隔开;content内容,base64编码(文件名1,文件base64编码串;文件名2,文件base64编码串);stime定时时间2010-07-05 17:37:00.返回:rrid
     * 
     * @param mobile
     * @param stime
     * @param sn
     * @param pwd
     * @param title
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/mdMmsSend")
    @WebResult(name = "mdMmsSendResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mdMmsSend", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdMmsSend")
    @ResponseWrapper(localName = "mdMmsSendResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdMmsSendResponse")
    public String mdMmsSend(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "title", targetNamespace = "http://tempuri.org/")
        String title,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        String stime);

    /**
     * 彩信发送：sn软件序列号;pwd加密密码md5(sn+password);title彩信主题;mobile手机号码,以英文逗号隔开;content内容,base64编码(文件名1,文件base64编码串;文件名2,文件base64编码串);stime定时时间2010-07-05 17:37:00.返回:rrid
     * 
     * @param ext
     * @param mobile
     * @param stime
     * @param sn
     * @param pwd
     * @param title
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "mdMmsSend_ex", action = "http://tempuri.org/mdMmsSend_ex")
    @WebResult(name = "mdMmsSend_exResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mdMmsSend_ex", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdMmsSendEx")
    @ResponseWrapper(localName = "mdMmsSend_exResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdMmsSendExResponse")
    public String mdMmsSendEx(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "title", targetNamespace = "http://tempuri.org/")
        String title,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        String stime,
        @WebParam(name = "ext", targetNamespace = "http://tempuri.org/")
        String ext);

    /**
     * 彩信发送：sn软件序列号;pwd加密密码md5(sn+password);title彩信主题;mobile手机号码,以英文逗号隔开;content内容,base64编码(文件名1,文件base64编码串utf8;文件名2,文件base64编码串utf8);stime定时时间2010-07-05 17:37:00.返回:rrid
     * 
     * @param ext
     * @param mobile
     * @param stime
     * @param sn
     * @param pwd
     * @param title
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "mdMmsSend_uex", action = "http://tempuri.org/mdMmsSend_uex")
    @WebResult(name = "mdMmsSend_uexResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mdMmsSend_uex", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdMmsSendUex")
    @ResponseWrapper(localName = "mdMmsSend_uexResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdMmsSendUexResponse")
    public String mdMmsSendUex(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "title", targetNamespace = "http://tempuri.org/")
        String title,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        String stime,
        @WebParam(name = "ext", targetNamespace = "http://tempuri.org/")
        String ext);

    /**
     * 彩信发送：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号码,以英文逗号隔开;content内容,base64编码(zip文件base64编码串);stime定时时间2010-07-05 17:37:00.返回:rrid
     * 
     * @param mobile
     * @param stime
     * @param sn
     * @param pwd
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/mdMmsSendF")
    @WebResult(name = "mdMmsSendFResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mdMmsSendF", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdMmsSendF")
    @ResponseWrapper(localName = "mdMmsSendFResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdMmsSendFResponse")
    public String mdMmsSendF(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        String stime);

    /**
     * 语音发送：sn软件序列号;pwd加密密码md5(sn+password);title语音主题;mobile手机号码,以英文逗号隔开,为空表示语音合成请求;txt文本内容;content文件内容,base64编码(wav文件名,文件base64编码串);srcnumber源号码;stime定时时间2010-07-05 17:37:00.返回:rrid
     * 
     * @param txt
     * @param mobile
     * @param srcnumber
     * @param stime
     * @param sn
     * @param pwd
     * @param title
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/mdAudioSend")
    @WebResult(name = "mdAudioSendResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mdAudioSend", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdAudioSend")
    @ResponseWrapper(localName = "mdAudioSendResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdAudioSendResponse")
    public String mdAudioSend(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "title", targetNamespace = "http://tempuri.org/")
        String title,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "txt", targetNamespace = "http://tempuri.org/")
        String txt,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "srcnumber", targetNamespace = "http://tempuri.org/")
        String srcnumber,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        String stime);

    /**
     * 传真发送：sn软件序列号;pwd加密密码md5(sn+password);title传真主题;mobile接收号码,以英文逗号隔开;content文件内容,base64编码(wav文件名,文件base64编码串);srcnumber发送号码;stime定时时间2010-07-05 17:37:00.返回:rrid
     * 
     * @param mobile
     * @param srcnumber
     * @param stime
     * @param sn
     * @param pwd
     * @param title
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/mdFaxSend")
    @WebResult(name = "mdFaxSendResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mdFaxSend", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdFaxSend")
    @ResponseWrapper(localName = "mdFaxSendResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdFaxSendResponse")
    public String mdFaxSend(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "title", targetNamespace = "http://tempuri.org/")
        String title,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "srcnumber", targetNamespace = "http://tempuri.org/")
        String srcnumber,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        String stime);

    /**
     * 彩信接收：sn软件序列号;pwd加密密码md5(sn+password).返回:彩信内容
     * 
     * @param sn
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/mdMmsReceive")
    @WebResult(name = "mdMmsReceiveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mdMmsReceive", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdMmsReceive")
    @ResponseWrapper(localName = "mdMmsReceiveResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MdMmsReceiveResponse")
    public String mdMmsReceive(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 发送短信：userId软件序列号;password加密密码md5(sn+password);pszMobis手机号列表，以逗号,隔开;pszMsg发送内容utf-8编码;iMobiCount手机号数量;pszSubPort扩展子号.返回:唯一标识
     * 
     * @param pszMsg
     * @param password
     * @param pszMobis
     * @param iMobiCount
     * @param pszSubPort
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MongateCsSpSendSmsNew", action = "http://tempuri.org/MongateCsSpSendSmsNew")
    @WebResult(name = "MongateCsSpSendSmsNewResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MongateCsSpSendSmsNew", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MongateCsSpSendSmsNew")
    @ResponseWrapper(localName = "MongateCsSpSendSmsNewResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MongateCsSpSendSmsNewResponse")
    public String mongateCsSpSendSmsNew(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        String userId,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "pszMobis", targetNamespace = "http://tempuri.org/")
        String pszMobis,
        @WebParam(name = "pszMsg", targetNamespace = "http://tempuri.org/")
        String pszMsg,
        @WebParam(name = "iMobiCount", targetNamespace = "http://tempuri.org/")
        int iMobiCount,
        @WebParam(name = "pszSubPort", targetNamespace = "http://tempuri.org/")
        String pszSubPort);

    /**
     * 接收短信：sn软件序列号;password加密密码md5(sn+password).
     * 
     * @param password
     * @param userId
     * @return
     *     returns com.ync365.seed.commons.sms.ArrayOfString
     */
    @WebMethod(operationName = "MongateCsGetSmsExEx", action = "http://tempuri.org/MongateCsGetSmsExEx")
    @WebResult(name = "MongateCsGetSmsExExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MongateCsGetSmsExEx", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MongateCsGetSmsExEx")
    @ResponseWrapper(localName = "MongateCsGetSmsExExResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MongateCsGetSmsExExResponse")
    public ArrayOfString mongateCsGetSmsExEx(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        String userId,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 回执：sn软件序列号;password加密密码md5(sn+password)
     * 
     * @param password
     * @param userId
     * @return
     *     returns com.ync365.seed.commons.sms.ArrayOfString
     */
    @WebMethod(operationName = "MongateCsGetStatusReportExEx", action = "http://tempuri.org/MongateCsGetStatusReportExEx")
    @WebResult(name = "MongateCsGetStatusReportExExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MongateCsGetStatusReportExEx", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MongateCsGetStatusReportExEx")
    @ResponseWrapper(localName = "MongateCsGetStatusReportExExResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.MongateCsGetStatusReportExExResponse")
    public ArrayOfString mongateCsGetStatusReportExEx(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        String userId,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 发送变量短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容utf-8编码;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字;bcode变量编码.返回:唯一标识
     * 
     * @param ext
     * @param mobile
     * @param stime
     * @param sn
     * @param pwd
     * @param bcode
     * @param content
     * @param rrid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/bianliang")
    @WebResult(name = "bianliangResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "bianliang", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.Bianliang")
    @ResponseWrapper(localName = "bianliangResponse", targetNamespace = "http://tempuri.org/", className = "com.ync365.seed.commons.sms.BianliangResponse")
    public String bianliang(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "ext", targetNamespace = "http://tempuri.org/")
        String ext,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        String stime,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        String rrid,
        @WebParam(name = "bcode", targetNamespace = "http://tempuri.org/")
        String bcode);

}
